[package]
name = "movei"
version = "0.1.0"
authors = ["move-hub <nonsense0202@pm.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
difference = "2.0"
ansi_term = "0.12"
clap = {git = "https://github.com/clap-rs/clap/"}
anyhow = "1.0.56"
reqwest = "0.10"
tokio = { version = "0.2", features = ["blocking"]}
toml = "0.5"
serde = "1.0"
itertools = "0.9.0"
walkdir = "2.3"

move-lang = "0.0.1"
move-core-types = "0.1.0"
move-vm-runtime = {version = "0.1.0", features = ["debug_module"]}
move-vm-types = "0.1.0"
# move-vm-state = "0.1.0"
move-ir-types = "0.1.0"
stdlib = "0.1.0"
libra-types = "0.1.0"
vm = "0.1.0"
bytecode-verifier = "0.1.0"
libra-crypto = "0.1.0"
resource-viewer = "0.1.0"
libra-state-view = "0.1.0"

dialect = {path = "../../api/dialect"}
movei-libra-dialect = {path = "../../dialect/libra"}
datatest = {path = "../../datatest"}
movei-test = {path = "../../movei-test"}
movei-libra-test = {path = "../../movei-test/movei-libra-test"}
movei-executor = {path = "../../movei-executor"}
movei-fmt = {path = "../../movei-fmt"}